USE bnbphotos;

-- LOAD DATA LOCAL INFILE '/Volumes/Seagate Backup Plus Drive/SDC_CSV_FILES/rooms.csv'
-- REPLACE INTO TABLE rooms
-- FIELDS TERMINATED BY ','
-- ENCLOSED BY ''
-- LINES TERMINATED BY '\n'
-- IGNORE 1 ROWS;

-- LOAD DATA LOCAL INFILE '/Volumes/Seagate Backup Plus Drive/SDC_CSV_FILES/photos1.csv'
-- REPLACE INTO TABLE photos
-- FIELDS TERMINATED BY ','
-- ENCLOSED BY ''
-- LINES TERMINATED BY '\n'
-- IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/Volumes/Seagate Backup Plus Drive/SDC_CSV_FILES/photos2000001.csv'
REPLACE INTO TABLE photos
FIELDS TERMINATED BY ','
ENCLOSED BY ''
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA LOCAL INFILE '/Volumes/Seagate Backup Plus Drive/SDC_CSV_FILES/photos4000001.csv'
REPLACE INTO TABLE photos
FIELDS TERMINATED BY ','
ENCLOSED BY ''
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/Volumes/Seagate Backup Plus Drive/SDC_CSV_FILES/photos6000001.csv'
REPLACE INTO TABLE photos
FIELDS TERMINATED BY ','
ENCLOSED BY ''
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/Volumes/Seagate Backup Plus Drive/SDC_CSV_FILES/photos8000001.csv'
REPLACE INTO TABLE photos
FIELDS TERMINATED BY ','
ENCLOSED BY ''
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

